import * as THREE from "three";
window.THREE = THREE;
import "../public/threejs/controls/OrbitControls";
import "../public/threejs/postprocessing/EffectComposer";
import "../public/threejs/postprocessing/MaskPass";
import "../public/threejs/postprocessing/RenderPass";
import "../public/threejs/postprocessing/ShaderPass";
import "../public/threejs/shaders/DotScreenShader";
import "../public/threejs/shaders/CopyShader";
import "../public/threejs/stats.min";
